site_name: JBMod Documentation
site_url: https://krolot.github.io/JBDevWiki/
repo_url: https://github.com/Krolot/JBDevWiki
repo_name: Krolot/JBDevWiki
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Welcome: index.md
  - Getting Started:
      - Building: getting-started/building.md
      - Debugging: getting-started/debugging.md
  - Game Development:
      - VScript: game/vscript.md

extra_css:
  - stylesheets/extra.css
